security:
  oauth2:
    client:
      clientId: 341382643444746
      clientSecret: 2f9257ae5cf58edbd8a3f452914d4656
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me